version: "3.7"
services:
  memcached:
    image: "memcached:alpine"

  redis:
    image: "redis:alpine"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql 
      PMA_USER: admin
      PMA_PASSWORD: admin
    ports:
      - "8001:80"
      
  mysql:
    image: "mysql:8.0"
    working_dir: /application
    volumes:
      - ".:/application"
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=cursephp
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
    ports:
      - "8002:3306"

  php-apache:
    depends_on:
      - mysql
    image: "php:8.1-apache"
    volumes:
      - "./htdocs/:/var/www/html/"
    ports:
      - 8000:80 
